# Call Journey Data Cleaning & EDA

In [7]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [8]:
%cd Downloads/CARdata

[Errno 2] No such file or directory: 'Downloads/CARdata'
/Users/lilaweiner/Downloads/CARdata

In [9]:
# reading in data

jan25_1 = pd.read_excel('CAR - EP, Flow, Activity, Queue, & Agent Names (01-12-25 - 01-18-25).xlsx', dtype=str, keep_default_na=False)
jan25_2 = pd.read_excel('CAR - EP, Flow, Activity, Queue, & Agent Names (01-19-25 - 02-01-25).xlsx', dtype=str, keep_default_na=False)
feb25_1 = pd.read_excel('CAR - EP, Flow, Activity, Queue, & Agent Names (02-02-25 - 02-15-25).xlsx', dtype=str, keep_default_na=False)
feb25_2 = pd.read_excel('CAR - EP, Flow, Activity, Queue, & Agent Names (02-16-25 - 03-01-25).xlsx', dtype=str, keep_default_na=False)
mar25_1 = pd.read_excel('CAR - EP, Flow, Activity, Queue, & Agent Names (03-02-25 - 03-15-25).xlsx', dtype=str, keep_default_na=False)
apr24_1 = pd.read_excel('CAR - EP, Flow, Activity, Queue, & Agent Names (04-07-24 - 04-20-24).xlsx', dtype=str, keep_default_na=False)
apr24_2 = pd.read_excel('CAR - EP, Flow, Activity, Queue, & Agent Names (04-21-24 - 05-04-24).xlsx', dtype=str, keep_default_na=False)
may24_1 = pd.read_excel('CAR - EP, Flow, Activity, Queue, & Agent Names (05-05-24 - 05-18-24).xlsx', dtype=str, keep_default_na=False)
may24_2 = pd.read_excel('CAR - EP, Flow, Activity, Queue, & Agent Names (05-19-24 - 06-01-24).xlsx', dtype=str, keep_default_na=False)
jun24_1 = pd.read_excel('CAR - EP, Flow, Activity, Queue, & Agent Names (06-02-24 - 06-15-24).xlsx', dtype=str, keep_default_na=False)
jun24_2 = pd.read_excel('CAR - EP, Flow, Activity, Queue, & Agent Names (06-16-24 - 06-29-24).xlsx', dtype=str, keep_default_na=False)
jul24_1 = pd.read_excel('CAR - EP, Flow, Activity, Queue, & Agent Names (06-30-24 - 07-13-24).xlsx', dtype=str, keep_default_na=False)
jul24_2 = pd.read_excel('CAR - EP, Flow, Activity, Queue, & Agent Names (07-14-24 - 07-27-24).xlsx', dtype=str, keep_default_na=False)
aug24_1 = pd.read_excel('CAR - EP, Flow, Activity, Queue, & Agent Names (07-28-24 - 08-10-24).xlsx', dtype=str, keep_default_na=False)
aug24_2 = pd.read_excel('CAR - EP, Flow, Activity, Queue, & Agent Names (08-11-24 - 08-24-24).xlsx', dtype=str, keep_default_na=False)
sep24_1 = pd.read_excel('CAR - EP, Flow, Activity, Queue, & Agent Names (08-24-24 - 09-07-24).xlsx', dtype=str, keep_default_na=False)
sep24_2 = pd.read_excel('CAR - EP, Flow, Activity, Queue, & Agent Names (09-08-24 - 09-21-24).xlsx', dtype=str, keep_default_na=False)
oct24_1 = pd.read_excel('CAR - EP, Flow, Activity, Queue, & Agent Names (09-22-24 - 10-05-24).xlsx', dtype=str, keep_default_na=False)
oct24_2 = pd.read_excel('CAR - EP, Flow, Activity, Queue, & Agent Names (10-06-24 - 10-19-24).xlsx', dtype=str, keep_default_na=False)
nov24_1 = pd.read_excel('CAR - EP, Flow, Activity, Queue, & Agent Names (10-20-24 - 11-02-24).xlsx', dtype=str, keep_default_na=False)
nov24_2 = pd.read_excel('CAR - EP, Flow, Activity, Queue, & Agent Names (11-03-24 - 11-16-24).xlsx', dtype=str, keep_default_na=False)
nov24_3 = pd.read_excel('CAR - EP, Flow, Activity, Queue, & Agent Names (11-17-24 - 11-30-24).xlsx', dtype=str, keep_default_na=False)
dec24_1 = pd.read_excel('CAR - EP, Flow, Activity, Queue, & Agent Names (12-01-24 - 12-14-24).xlsx', dtype=str, keep_default_na=False)
dec24_2 = pd.read_excel('CAR - EP, Flow, Activity, Queue, & Agent Names (12-15-24 - 12-28-24).xlsx', dtype=str, keep_default_na=False)
dec24_3 = pd.read_excel('CAR - EP, Flow, Activity, Queue, & Agent Names (12-29-24 - 01-11-25).xlsx', dtype=str, keep_default_na=False)

In [156]:
#looking at the data
jan25_2.head()

,Time Zone: (UTC-05:00) Central Daylight Time (America/Chicago),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6
0,,,,,,,
1,Contact Session ID,EP Name,Flow Name,Activity Name,Activity Start Timestamp,Queue Name,Agent Name
2,3a80bd36-09dc-4d3e-970f-f28b717a3b86,Main Number Telephony EP,N/A,N/A,2025/01/19 12:45:16 AM,N/A,N/A
3,3a80bd36-09dc-4d3e-970f-f28b717a3b86,N/A,LACMain,N/A,2025/01/19 12:45:16 AM,N/A,N/A
4,3a80bd36-09dc-4d3e-970f-f28b717a3b86,Main Number Telephony EP,N/A,LanguageSelectionMenu,2025/01/19 12:45:16 AM,N/A,N/A

In [10]:
# cleaning function

def clean(df):
    df.columns = df.iloc[1] #correcting column names
    new = df.iloc[2:].reset_index(drop = True)

    new.replace('N/A', pd.NA, inplace=True) #True NA values, instead of "NA" string
    new.fillna(method='ffill', inplace=True)
    return new

In [11]:
# cleaning dfs

xjan25_1 = clean(jan25_1)
xjan25_2 = clean(jan25_2)
xfeb25_1 = clean(feb25_1)
xfeb25_2 = clean(feb25_2)
xmar25_1 = clean(mar25_1)
xapr24_1 = clean(apr24_1)
xapr24_2 = clean(apr24_2)
xmay24_1 = clean(may24_1)
xmay24_2 = clean(may24_2)
xjun24_1 = clean(jun24_1)
xjun24_2 = clean(jun24_2)
xjul24_1 = clean(jul24_1)
xjul24_2 = clean(jul24_2)
xaug24_1 = clean(aug24_1)
xaug24_2 = clean(aug24_2)
xsep24_1 = clean(sep24_1)
xsep24_2 = clean(sep24_2)
xoct24_1 = clean(oct24_1)
xoct24_2 = clean(oct24_2)
xnov24_1 = clean(nov24_1)
xnov24_2 = clean(nov24_2)
xnov24_3 = clean(nov24_3)
xdec24_1 = clean(dec24_1)
xdec24_2 = clean(dec24_2)
xdec24_3 = clean(dec24_3)

In [12]:
# list of cleaned dfs

all_data = [xjan25_1 ,xjan25_2 ,xfeb25_1 ,xfeb25_2 ,xmar25_1 ,xapr24_1 ,xapr24_2 ,xmay24_1 ,xmay24_2 ,xjun24_1 ,xjun24_2 
,xjul24_1, xjul24_2 ,xaug24_1 ,xaug24_2 ,xsep24_1 ,xsep24_2 ,xoct24_1 ,xoct24_2 ,xnov24_1 ,xnov24_2 
,xnov24_3 ,xdec24_1 ,xdec24_2 ,xdec24_3 ]

len(all_data)

25

In [13]:
# concatenating the list of clean dfs 
combined = pd.DataFrame(columns=xjan25_1.columns)

for dataset in all_data:
    combined = pd.concat([combined, dataset[:len(dataset) - 1]], axis = 0)

In [14]:
combined.head()

1,Contact Session ID,EP Name,Flow Name,Activity Name,Activity Start Timestamp,Queue Name,Agent Name
0,1cecb817-00fa-433a-9ec5-4bc306b42a78,Main Number Telephony EP,<NA>,<NA>,2025/01/12 12:36:38 AM,<NA>,<NA>
1,1cecb817-00fa-433a-9ec5-4bc306b42a78,Main Number Telephony EP,LACMain,<NA>,2025/01/12 12:36:38 AM,<NA>,<NA>
2,1cecb817-00fa-433a-9ec5-4bc306b42a78,Main Number Telephony EP,LACMain,LanguageSelectionMenu,2025/01/12 12:36:38 AM,<NA>,<NA>
3,1cecb817-00fa-433a-9ec5-4bc306b42a78,Main Number Telephony EP,LACMain,LanguageSelectionMenu,2025/01/12 12:36:39 AM,<NA>,<NA>
4,1cecb817-00fa-433a-9ec5-4bc306b42a78,Main Number Telephony EP,LACMain,LanguageSelectionMenu,2025/01/12 12:36:40 AM,<NA>,<NA>

In [15]:
# Changing time column to DateTime

combined['Activity Start Timestamp'] = pd.to_datetime(combined['Activity Start Timestamp'])

In [18]:
# Weekend vs weekday

combined['day_type'] = combined['Activity Start Timestamp'].dt.dayofweek.apply(lambda x: 'Weekend' if x >= 5 else 'Weekday')

In [22]:
# Building out separate time columns (not necessary)
combined['hour'] = combined['Activity Start Timestamp'].dt.hour

combined['day_of_week'] = combined['Activity Start Timestamp'].dt.day_name()

combined['day_of_month'] = combined['Activity Start Timestamp'].dt.day

combined['month'] = combined['Activity Start Timestamp'].dt.month_name()

In [23]:
#work hours or not
combined['work_hours_flag'] = combined['Activity Start Timestamp'].dt.hour.apply(
    lambda x: 'in work hours' if 8 <= x < 17 else 'out of work hours'
)

In [24]:
combined.head()

1,Contact Session ID,EP Name,Flow Name,Activity Name,Activity Start Timestamp,Queue Name,Agent Name,day_type,hour,day_of_week,day_of_month,month,work_hours_flag
0,1cecb817-00fa-433a-9ec5-4bc306b42a78,Main Number Telephony EP,<NA>,<NA>,2025-01-12 00:36:38,<NA>,<NA>,Weekend,0,Sunday,12,January,out of work hours
1,1cecb817-00fa-433a-9ec5-4bc306b42a78,Main Number Telephony EP,LACMain,<NA>,2025-01-12 00:36:38,<NA>,<NA>,Weekend,0,Sunday,12,January,out of work hours
2,1cecb817-00fa-433a-9ec5-4bc306b42a78,Main Number Telephony EP,LACMain,LanguageSelectionMenu,2025-01-12 00:36:38,<NA>,<NA>,Weekend,0,Sunday,12,January,out of work hours
3,1cecb817-00fa-433a-9ec5-4bc306b42a78,Main Number Telephony EP,LACMain,LanguageSelectionMenu,2025-01-12 00:36:39,<NA>,<NA>,Weekend,0,Sunday,12,January,out of work hours
4,1cecb817-00fa-433a-9ec5-4bc306b42a78,Main Number Telephony EP,LACMain,LanguageSelectionMenu,2025-01-12 00:36:40,<NA>,<NA>,Weekend,0,Sunday,12,January,out of work hours

# Combined Data: Week 4 EDA

In [25]:
# Downloading for tableau 
combined.to_csv('combined_05222025_.csv')

In [161]:
combined.shape

(2075533, 7)

- 2,075,533 rows
- 7 columns